const hydroFabricActionsTypes = {
    set_nexus_id: 'SET_NEXUS_ID',
    set_nexus_series: 'SET_NEXUS_SERIES',
    set_nexus_list: 'SET_NEXUS_LIST',
    set_catchment_series: 'SET_CATCHMENT_SERIES',
    set_catchment_list: 'SET_CATCHMENT_LIST',
    set_catchment_id: 'SET_CATCHMENT_ID',
    set_catchment_variable: 'SET_CATCHMENT_VARIABLE',
    set_catchment_variable_list: 'SET_CATCHMENT_VARIABLE_LIST',
    set_troute_series: 'SET_TROUTE_SERIES',
    set_troute_id: 'SET_TROUTE_ID',
    set_troute_variable: 'SET_TROUTE_VARIABLE',
    set_troute_variable_list: 'SET_TROUTE_VARIABLE_LIST',
    set_teehr_series: 'SET_teehr_SERIES',
    set_teehr_id: 'SET_teehr_ID',
    set_teehr_variable: 'SET_teehr_VARIABLE',
    set_teehr_variable_list: 'SET_teehr_VARIABLE_LIST',
    set_reset_teehr: 'SET_RESET_teehr',
    reset_nexus: 'RESET_NEXUS',
    reset_catchment: 'RESET_CATCHMENT',
    reset_troute: 'RESET_TROUTE',
    reset: 'RESET',
    set_series: 'SET_SERIES',
};

export { hydroFabricActionsTypes }