apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ngiab-calibration-run
  namespace: argo
spec:
  entrypoint: main
  templates:
  - name: run-cal
    inputs:
      parameters:
        - { name: input_bucket,  default: "" }
        - { name: input_key,     default: "" }
        - { name: input_subdir,  default: "" }
        - { name: output_bucket, default: "test-ngen" }
        - { name: output_prefix, default: "demo/default" }
      artifacts:
        - name: calibration-prepared
          path: /tmp/in/calibration-prepared.tgz
          s3:
            endpoint: s3.amazonaws.com
            region: us-east-1
            bucket: "{{inputs.parameters.input_bucket}}"
            key: "{{inputs.parameters.input_key}}"
            accessKeySecret: { name: aws-creds, key: AWS_ACCESS_KEY_ID }
            secretKeySecret:  { name: aws-creds, key: AWS_SECRET_ACCESS_KEY }
    script:
      image: awiciroh/ngiab-cal:latest
      command: [bash, -lc]
      env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom: { secretKeyRef: { name: aws-creds, key: AWS_ACCESS_KEY_ID } }
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom: { secretKeyRef: { name: aws-creds, key: AWS_SECRET_ACCESS_KEY } }
      - name: AWS_DEFAULT_REGION
        value: us-east-1
      source: |
        set -euo pipefail
        DATA_DIR="/ngen/ngen/data"
        tar -C "$DATA_DIR" -xzf /tmp/in/calibration-prepared.tgz
        set +o pipefail
        /calibration/run.sh
        tar -C "$(dirname "$DATA_DIR")" -czf /tmp/out/calibrated.tgz "$(basename "$DATA_DIR")"
    outputs:
      artifacts:
      - name: calibrated
        path: /tmp/out/calibrated.tgz
        archive:
            none: {}        
        s3:
          endpoint: s3.amazonaws.com
          region: us-east-1
          bucket: "{{inputs.parameters.output_bucket}}"
          key: "{{inputs.parameters.output_prefix}}/calibrated.tgz"
          accessKeySecret: { name: aws-creds, key: AWS_ACCESS_KEY_ID }
          secretKeySecret:  { name: aws-creds, key: AWS_SECRET_ACCESS_KEY }
