// features/workflows/store/actions/actionsTypes.js
export const types = {
  SET_NODES: 'SET_NODES',
  SET_EDGES: 'SET_EDGES',
  NODES_CHANGE: 'NODES_CHANGE',
  EDGES_CHANGE: 'EDGES_CHANGE',
  ADD_EDGE: 'ADD_EDGE',
  ADD_NODE: 'ADD_NODE',
  REMOVE_SELECTED: 'REMOVE_SELECTED',

  // Execution + WS
  WORKFLOW_COMPILED: 'WORKFLOW_COMPILED',
  WORKFLOW_SENT: 'WORKFLOW_SENT',
  UPDATE_NODE_STATUS: 'UPDATE_NODE_STATUS',

  WS_CONNECTED: 'WS_CONNECTED',
  WS_DISCONNECTED: 'WS_DISCONNECTED',
  WS_ERROR: 'WS_ERROR',
  WS_MESSAGE: 'WS_MESSAGE',

  // Playback
  PLAYBACK_LOAD: 'PLAYBACK_LOAD',   // payload: { events }
  PLAYBACK_START: 'PLAYBACK_START',
  PLAYBACK_PAUSE: 'PLAYBACK_PAUSE',
  PLAYBACK_RESET: 'PLAYBACK_RESET',
  PLAYBACK_TICK: 'PLAYBACK_TICK',
};
